feat: support for OpenVINO 2025.4 (#994)
---
Original author: Amin <muhammad.al.amin.amali.mazlan@intel.com>

diff --git a/src/esq/suites/ai/gen/src/containers/ovms_server/Dockerfile b/src/esq/suites/ai/gen/src/containers/ovms_server/Dockerfile
--- a/src/esq/suites/ai/gen/src/containers/ovms_server/Dockerfile
+++ b/src/esq/suites/ai/gen/src/containers/ovms_server/Dockerfile
@@ -1,7 +1,7 @@
 # Copyright (C) 2025 Intel Corporation
 # SPDX-License-Identifier: Apache-2.0
 
-FROM openvino/model_server:2025.3-gpu
+FROM openvino/model_server:2025.4.1-gpu
 
 USER root
 RUN apt-get update \
@@ -9,6 +9,12 @@ RUN apt-get update \
         software-properties-common \
         curl \
     && rm -rf /var/lib/apt/lists/*
+
+# Update NPU drivers to latest version
+RUN curl -O https://raw.githubusercontent.com/open-edge-platform/edge-developer-kit-reference-scripts/49473c01212ee84c53b0cff75581d0c9b6201794/npu_installer.sh 
+RUN chmod +x ./npu_installer.sh 
+# Create udev directory for container environment and run installer (ignore udev reload failures)
+RUN mkdir -p /etc/udev/rules.d && ./npu_installer.sh || true
 
 USER ovms
 
